import type { Metadata } from "next";
import { BasicLayout } from "@/app";
import { PropsWithChildren } from "react";
import { Figtree } from "next/font/google";
import { cls } from "@/shared";

import "./globals.css";

const figtree = Figtree({
  weight: "variable",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={cls(figtree.className, "bg-white dark:bg-dark-palette-900")}
      >
        <BasicLayout>{children}</BasicLayout>
      </body>
    </html>
  );
}
