import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { PORTAL_ID } from "@/global.constant";
import { Providers } from "./providers";

const inter = Figtree({ weight: "300", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div id={PORTAL_ID.TOTAL_PORTAL} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
