import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

import { PORTAL_ID } from "@/global.constant";
import { Providers } from "./providers";
import { mergeCls } from "@/utils/cls";
import { Toast } from "@/components/Toast/Toast";

const figtree = Figtree({
  weight: "variable",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={mergeCls(
          figtree.className,
          "bg-white dark:bg-dark-palette-900"
        )}
      >
        <Providers>
          <div id={PORTAL_ID.TOTAL_PORTAL} />
          <Toast />
          {children}
        </Providers>
      </body>
    </html>
  );
}
